import { LegalLayout } from '../../components/legal/LegalLayout';

export default function Privacy() {
  return <LegalLayout eyebrow="Privacy Policy" title="Privacy should be the default, not an upgrade." intro="This V1 policy explains what NoMeta processes, what it intentionally avoids collecting, and what changes when you create an account or make a payment.">
    <section><h2>1. What NoMeta does</h2><p>NoMeta scans and cleans supported images in the browser. The intended core workflow processes the image locally on your device and returns a cleaned copy for you to download.</p></section>
    <section><h2>2. Images and metadata</h2><p>For the core V1 cleaning workflow, NoMeta is designed not to upload or store your original image. Metadata exposed by the scanner is processed in your browser for the purpose of showing you privacy risks and creating a cleaned image.</p><p>Because browser behavior, extensions, network configuration and future product changes can vary, the local-processing promise applies to the implemented V1 core workflow and should not be interpreted as a guarantee about every future feature.</p></section>
    <section><h2>3. Account information</h2><p>If you register, we may process account identifiers such as your email address, authentication identifiers, account status and timestamps needed to operate your account. We do not need the original image to maintain your account.</p></section>
    <section><h2>4. Usage and product records</h2><p>To enforce the V1 allowance of two successful free cleanings per calendar day and manage paid credits, the service may store usage counters, credit balances, ledger entries and transaction identifiers. These records are not intended to contain image files or EXIF payloads.</p></section>
    <section><h2>5. Payments</h2><p>Payments are intended to be processed by Razorpay. NoMeta should receive only the payment and order information required to verify a transaction, credit an account and maintain financial records. Card, UPI or banking credentials should be entered only in the payment provider's secure checkout.</p></section>
    <section><h2>6. Analytics</h2><p>If analytics are enabled, they should be configured to measure product performance without collecting original images, thumbnails, GPS coordinates or raw EXIF payloads. Analytics configuration will be disclosed before production use.</p></section>
    <section><h2>7. Cookies and local storage</h2><p>Authentication may use a secure, HTTP-only session cookie. Any strictly necessary storage used for product functionality should be limited to that purpose. See <a href="/data-and-cookies">Data &amp; cookies</a> for the V1 data map.</p></section>
    <section><h2>8. Retention and deletion</h2><p>We intend to retain account, usage and payment records only as long as needed for the service, security, fraud prevention, accounting or legal obligations. Account deletion should remove or anonymize data that NoMeta no longer needs, subject to records we are legally required to retain.</p></section>
    <section><h2>9. Security</h2><p>NoMeta is designed around data minimization. See <a href="/security">Security</a> for the product's security principles and responsible disclosure route.</p></section>
    <section><h2>10. Changes</h2><p>This policy may be updated as NoMeta adds features. Material changes should be reflected on this page with an updated effective date before the changed practice is introduced.</p></section>
    <section><h2>Effective date</h2><p>September 7, 2026. This is a V1 product policy draft and should be reviewed for the final operating entity, jurisdiction and production configuration before launch.</p></section>
  </LegalLayout>;
}
